services:
  database:
    image: mysql:8.2
    environment:
      MYSQL_DATABASE: email-distributor
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    restart: always

volumes:
  db-data:
