openapi: "3.0.0"
info:
  version: 1.0.0
  title: EMail Distributor
  description: OpenAPI 3.0 specification
servers:
  - url: /api
paths:
  /send:
    post:
      summary: Send EMail
      operationId: sendEmail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendEmail"
      responses:
        "200":
          description: success
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    SendEmail:
      required:
        - name
      properties:
        title:
          type: string
        toEmailAddress:
          type: string
        fromEmailAddress:
          type: string
        body:
          type: object
          properties:
            text:
              type: string
            html:
              type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
