FROM golang:1.21.1-alpine

ARG GIT_VERSION
ARG GIT_REVISION
ARG GIT_BUILD

WORKDIR /app

ENV GOEXPERIMENTALS=loopvar

COPY go.mod go.sum ./
RUN go mod download

COPY . ./
RUN go build \
    -o batch-send \
    -ldflags " \
    -X main.version=$GIT_VERSION \
    -X main.revision=$GIT_REVISION \
    -X main.build=$GIT_BUILD \
    "
