// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xTzW7bPBB8FWG/70hISnLjLUV9yKFogR6DHGhyZTMQf7q7KmwYeveClOw0sYteevJ6",
	"/2Y4szqBTSGniFEY9AnY7jGYGm6IEpUgU8pI4rGmbXJYfh2yJZ/Fpwh6aW5qTcGQKBgBDT7Kwz0okGPG",
	"5S/ukGBWEJDZ7P646Fy+jLKQjzuYZwWEPyZP6EA/wwp4bn+ZFXzH6DbB+PGa+ja543V2L6H2fkBSIHiQ",
	"G4X5QiptX9FKaR0ohQr66Bwh8+19Xka8XUl/Gf7w7GhCeWxJ+zikaxW/ZoyP356ah7ZvOKP1g7em1i40",
	"YPPF+LH57AvGdpJEoOAnEi8b7tq+7Qu3lDGa7EHDQ3vX9qAgG9lXkh1jdFXQxFWpImuFeXKgf3NiYY8s",
	"n1YHbIqCsc6YnMeVXPfKBft8hSX6n3AADf91b2farTfave2f3wskNGFNcE6RF5fv+/5aJp6sLYLPChwO",
	"Zhrln5Fbvp5K7D3mFPGQ0Qq6BtceBTyFYOi4itZUa5ZhRiqmgH4+wUQjaNiLZNZdhwcT8oitTaErBs0v",
	"868AAAD//xo/qAPOAwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
