// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.2 DO NOT EDIT.
package openapi

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int32 `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// SendEmail defines model for SendEmail.
type SendEmail struct {
	Body *struct {
		Html *string `json:"html,omitempty"`
		Text *string `json:"text,omitempty"`
	} `json:"body,omitempty"`
	FromEmailAddress *string `json:"fromEmailAddress,omitempty"`
	Title            *string `json:"title,omitempty"`
	ToEmailAddress   *string `json:"toEmailAddress,omitempty"`
}

// SendEmailJSONRequestBody defines body for SendEmail for application/json ContentType.
type SendEmailJSONRequestBody = SendEmail
